### PR TITLE
changed Husky tire to 13 inches (0.3302m)

### PR DESCRIPTION
**Pull request by majcote**

### CODE REVIEW

**Review by UltronDestroyer — DISMISSED** [review]
Did we change wheel sizes? Which robot was the wheel size tested on?

**Comment by majcote** [comment]
It seems it's always been incorrect, A customer has reported currently 1 revolution does not report 2 pi radians. 

Husky uses a Carlisle: Super Lug 13/5.00-6, which is 13 inches

**Comment by paulbovbel** [comment]
FYI https://github.com/husky/husky/blob/c81085ee8f62ddd2acaf9148585e2d606ff07b23/husky_description/urdf/husky.urdf.xacro#L61

**Comment by UltronDestroyer** [comment]
How is that not applicable? The URDF should be updated too. We need to be sure this is is true for more than one customer and more than one robot.. I'm going to go measure out back.

**Review by tonybaltovski — APPROVED** [review]

**Comment by UltronDestroyer** [comment]
@tonybaltovski Why did you force merge this? Do we know this is the case for all Huskys? URDF needs to be update to as the sim needs to reflect it accurately.

**Comment by tonybaltovski** [comment]
LGTM @majcote.  Update the main husky repo for kinetic and indigo.

**Comment by UltronDestroyer** [comment]
Ermh, https://github.com/husky/husky/blob/c81085ee8f62ddd2acaf9148585e2d606ff07b23/husky_description/urdf/husky.urdf.xacro#L61 still stands.. Not sure why this is merged.

**Comment by tonybaltovski** [comment]
@TheDash that is the correct wheel size.

**Comment by UltronDestroyer** [comment]
Wheel radius: 0.17705
Wheel diameter: 0.3302

You tryin' to tell me that 0.17705*2 is 0.3302?

**Comment by majcote** [comment]
It's a different package, I'm making a PR for it now

**Comment by UltronDestroyer** [comment]
Ah, yeah. Husky_robot is deprecated.

**Pull request merged**
